---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: subtitle
  label: subtitle
- type: textarea
  name: description
  label: description
- type: datetime
  name: date
  label: date
- type: file
  name: featured_image
  label: featured_image
