---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: subtitle
  label: subtitle
- type: textarea
  name: description
  label: description
- type: datetime
  name: date
  label: date
- type: file
  name: featured_image
  label: featured_image
pages:
- _projects/argon-jekyll-theme.md
- _projects/coastapp.md
- _projects/positivity.md
- _projects/ppp-calculator.md
- _projects/table-co.md
